package com.docscanner.ui

import android.graphics.Bitmap
import androidx.lifecycle.SavedStateHandle
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.docscanner.domain.model.Document
import com.docscanner.domain.model.Page
import com.docscanner.domain.usecase.SaveDocumentUseCase
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

@RunWith(AndroidJUnit4::class)
class ScannerFlowTest {

    private val plentifulStorage: (File) -> Long = { Long.MAX_VALUE }

    private fun makeUseCase(docCount: Int = 0, pageCount: Int = 0) =
        SaveDocumentUseCase(FakeRepo(docCount, pageCount), File("/fake"), plentifulStorage)

    // SaveDocumentUseCase happy paths

    @Test
    fun createDocumentReturnsDocumentWithAutoGeneratedName() = runBlocking {
        val repo = FakeRepo()
        SaveDocumentUseCase(repo, File("/fake"), plentifulStorage).createDocument(fakeBitmap())
        assertNotNull(repo.createdName)
        assertTrue("Expected 'Document ...' prefix", repo.createdName!!.startsWith("Document "))
    }

    @Test
    fun addPageRoutesToCorrectDocumentId() = runBlocking {
        val repo = FakeRepo(pageCountForDoc = 5)
        SaveDocumentUseCase(repo, File("/fake"), plentifulStorage).addPage("existing-doc", fakeBitmap())
        assertEquals("existing-doc", repo.addedDocumentId)
    }

    // ScannerViewModel state transitions — no lambda, so backtick names are fine here

    @Test
    fun onScanCancelledSetsNavigateBackTrue() {
        val vm = makeScannerViewModel()
        vm.onScanCancelled()
        assertTrue(vm.uiState.value.navigateBack)
    }

    @Test
    fun onScanErrorStoresMessageInErrorMessage() {
        val vm = makeScannerViewModel()
        vm.onScanError("something went wrong")
        assertEquals("something went wrong", vm.uiState.value.errorMessage)
    }

    @Test
    fun clearErrorClearsErrorMessage() {
        val vm = makeScannerViewModel()
        vm.onScanError("err")
        vm.clearError()
        assertNull(vm.uiState.value.errorMessage)
    }

    @Test
    fun initialStateHasNoSavedDocumentIdAndNoError() {
        val vm = makeScannerViewModel()
        assertNull(vm.uiState.value.savedDocumentId)
        assertNull(vm.uiState.value.errorMessage)
        assertTrue(!vm.uiState.value.navigateBack)
    }

    // Helpers

    private fun fakeBitmap() = Bitmap.createBitmap(10, 10, Bitmap.Config.ARGB_8888)

    private fun makeScannerViewModel() =
        com.docscanner.ui.scanner.ScannerViewModel(
            makeUseCase(),
            SavedStateHandle(mapOf("documentId" to "new"))
        )

    private class FakeRepo(
        private val docCount: Int = 0,
        private val pageCountForDoc: Int = 0
    ) : com.docscanner.data.repository.DocumentRepository {
        var createdName: String? = null
        var addedDocumentId: String? = null
        override fun getAllDocuments(): Flow<List<Document>> = flowOf(emptyList())
        override suspend fun getDocumentById(id: String): Document? = null
        override suspend fun createDocument(name: String, bitmap: Bitmap): Document {
            createdName = name; return Document("id", name, 0L, 0L, 1, null)
        }
        override suspend fun addPage(documentId: String, bitmap: Bitmap): Page {
            addedDocumentId = documentId; return Page("p", documentId, 1, "/p", 0L)
        }
        override suspend fun updatePage(id: String, page: Page, bitmap: Bitmap): Page = page
        override suspend fun reorderPages(id: String, pages: List<Page>) {}
        override suspend fun deleteDocument(id: String) {}
        override suspend fun deletePage(id: String, pageId: String) {}
        override suspend fun renameDocument(id: String, name: String) {}
        override suspend fun getDocumentCount(): Int = docCount
        override suspend fun getPageCount(id: String): Int = pageCountForDoc
        override suspend fun getPagesForDocument(id: String): List<Page> = emptyList()
        override suspend fun exportPdf(id: String): File = File("/fake.pdf")
        override fun pageFileExists(path: String): Boolean = true
    }
}
